export const SET_IS_NEW_FEEDBACK_DIALOG_OPEN =
  "SET_IS_NEW_FEEDBACK_DIALOG_OPEN";
export const SET_NEW_FEEDBACK_TITLE_NAME = "SET_NEW_FEEDBACK_TITLE_NAME";
export const CREATE_FORM = "CREATE_FORM";
export const ADD_FIELD_TO_FORM = "ADD_FIELD_TO_FORM";
export const REMOVE_FIELD = "REMOVE_FIELD";
export const SET_FIELD_VALUE = "SET_FIELD_VALUE";